### PR TITLE
January Update to mainspring

### PR DESCRIPTION
**Pull request by sgalindo2388**
Updated base, atoms, molecules, organisms, layouts and utilities.

---
This change is [Reviewable](https://reviewable.io/reviews/fosterinteractive/mainspring/11)

### CODE REVIEW

**Comment by finteractive** [comment]
Reviewed 269 of 397 files at r1.
Review status: 236 of 341 files reviewed at latest revision, 14 unresolved discussions.

---

*[components/_patterns/00-base/08-html/_html.scss, line 27 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4XVIwyG1JP1GswUg:-L3A4UOVc-4TRoYKZxBa:btkg3z7) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/00-base/08-html/_html.scss#L27)):*
> https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
ADD in the suggestion from the post and delete the comment


``` 
html {
CODE

*, *:before, *:after {
  box-sizing: inherit;
}
}
```


---

*[components/_patterns/01-atoms/_field-wysiwyg.twig, line 41 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4nm1y0zhGN8qkVby:-L3A4nm1y0zhGN8qkVbz:bupl0eo) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/_field-wysiwyg.twig#L41)):*
> ```Twig
>  @TODO: THIS CAN BE REMOVED IF BEM CLASSES CAN BE APPLIED IN WYSIWYG
> #}
> ```

Try deleting. Field default template probably is fine

---

*[components/_patterns/01-atoms/00-type/00-heading.twig, line 11 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4zxmC7W3VTZx7zTA:-L3A4zxmC7W3VTZx7zTB:b-wnpg4a) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/00-heading.twig#L11)):*
> ```Twig
>   {# Allow for a div to be used instead of a heading #}
>   {% set level = level == 'h0' ? 'div' : level %}
>   {% set variation = '__h' ~ (heading.variation|default(heading.level|default('2'))) %}
> ```

Add a line to set the icon and then call the var when used

{% set icon_name= icon_name|default('#ico-angle-right') %}

Replace x2 strings in content with var

---

*[components/_patterns/01-atoms/00-type/_headings.scss, line 94 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A5it-tAx5jx7-j5HL:-L3A5it-tAx5jx7-j5HM:b-9xfxmy) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/_headings.scss#L94)):*
> ```SCSS
>   @extend %heading--core;
>   @include font-size($h3-font-sizes, 0, 1);
>   font-weight: 700;
> ```

Replace 700's with 600's

---

*[components/_patterns/01-atoms/01-svg/_svg.scss, line 90 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A69YyTram9axCPpbz:-L3A69YyTram9axCPpc-:b-5qdsot) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/01-svg/_svg.scss#L90)):*
> ```SCSS
> .a-svg-inline-left {
>   // @extend %c-btn--icon-core;
>   // See /global/g-svg/_g-svg--mixins.scss
> ```

Update the references to "global" folder

---

*[components/_patterns/01-atoms/button/_buttons--icon.scss.todo, line 0 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A6Yf6nzZzVsua6_tg:-L3A6Yf6nzZzVsua6_th:bs2dogg) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/button/_buttons--icon.scss.todo#L0)):*
Delete

---

*[components/_patterns/01-atoms/date/_date.scss, line 2 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A6nhaF5RlerUmb_NB:-L3A6nhaF5RlerUmb_NC:bfwcgtk) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/date/_date.scss#L2)):*
> ```SCSS
> // .a-date {
> ```

Does this look OK in the PL? If not Add something like a-type--small ?

---

*[components/_patterns/01-atoms/form-element/_form.scss, line 1 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A858GbPMO2yOUt8gl:-L3A858GbPMO2yOUt8gm:b-npdt15) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/_form.scss#L1)):*
> ```SCSS
> /* Form Elements Reset
> ```

Move to base/resets

---

*[components/_patterns/01-atoms/form-element/_form.scss, line 61 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A7UitzlO43b8AmCIh:-L3A7UitzlO43b8AmCIi:bne90li) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/_form.scss#L61)):*
> ```SCSS
>   border-color: palette(blue, xlight);
>   background-color: $white;
>   box-shadow: none;
> ```

comment out all form focus overrides
outline and box-shadow

 resets and add a reference to this post -https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/

---

*[components/_patterns/01-atoms/form-element/input/_input.scss, line 5 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A8Rn40O3BtgDZFzJY:-L3A8Rn40O3BtgDZFzJZ:bk4r110) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/input/_input.scss#L5)):*
> ```SCSS
>   border-color: palette(grey, light);
>   padding: ru(0.5);
>   -webkit-appearance: none;
> ```

move to reset

---

*[components/_patterns/01-atoms/form-element/input/_input.scss, line 26 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A8UUAuzRTdTnLCo1h:-L3A8UUAuzRTdTnLCo1i:bvcfpit) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/input/_input.scss#L26)):*
> ```SCSS
>   padding: 0;
>   white-space: normal;
>   -webkit-appearance: none;
> ```

move to reset on input

---

*[components/_patterns/01-atoms/table/_tables.scss, line 25 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ABgF_Jal52uMtFBrs:-L3ABgF_Jal52uMtFBrt:b-rmm1vv) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/table/_tables.scss#L25)):*
> ```SCSS
>   padding-bottom: ru(0.25);
>   color: $white;
>   font-weight: 500;
> ```

600 (make all weights in this P  either 400 or 600)

---

*[components/_patterns/02-molecules/accordion-item/accordion-item.twig, line 6 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ABskLCA6sSQYZDvZD:-L3ABskLCA6sSQYZDvZE:b-u9p8mw) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/02-molecules/accordion-item/accordion-item.twig#L6)):*
> ```Twig
>     <div class="m-accordion-item__label-text">{{ accordion_label }}</div>
>     <div class="m-accordion-item__label-icon">
> {#       <svg class="svg__core m-accordion-item__svg--expand"><use xlink:href="{{ base_path ~ directory }}/assets/svg/sprite-ui.svg#ico-chevron-down"></use></svg>
> ```

remove comment

---

*[components/_patterns/08-vendor/_flickity.scss, line 1 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ADWg21BYia9LgNzcl:-L3ADWg21BYia9LgNzcm:bbsvmnw) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/08-vendor/_flickity.scss#L1)):*
> ```SCSS
> // sass-lint:disable-all
> ```

REMOVE and replace with code  insert default styles from "https://flickity.metafizzy.co"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11)*

**Comment by sgalindo2388** [comment]
Review status: 236 of 341 files reviewed at latest revision, 14 unresolved discussions.

---

*[components/_patterns/00-base/08-html/_html.scss, line 27 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4XVIwyG1JP1GswUg:-L3DyV8yLx7cp7l7ge61:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/00-base/08-html/_html.scss#L27)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

> https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/
ADD in the suggestion from the post and delete the comment


``` 
html {
CODE

*, *:before, *:after {
  box-sizing: inherit;
}
}

</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/_field-wysiwyg.twig, line 41 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4nm1y0zhGN8qkVby:-L3DycoLdoXj_47CAWdO:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/_field-wysiwyg.twig#L41)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Try deleting. Field default template probably is fine
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/00-type/00-heading.twig, line 11 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4zxmC7W3VTZx7zTA:-L3DzluZAXdq3A214aZG:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/00-heading.twig#L11)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Add a line to set the icon and then call the var when used

{% set icon_name= icon_name|default('#ico-angle-right') %}

Replace x2 strings in content with var
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/00-type/_headings.scss, line 94 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A5it-tAx5jx7-j5HL:-L3E-2ZU3KKwGuMse8K4:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/_headings.scss#L94)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Replace 700's with 600's
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/01-svg/_svg.scss, line 90 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A69YyTram9axCPpbz:-L3E0IObkwH85f04l69p:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/01-svg/_svg.scss#L90)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Update the references to "global" folder
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/button/_buttons--icon.scss.todo, line  at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A6Yf6nzZzVsua6_tg:-L3E0U_8yerJwXltB_7m:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/button/_buttons--icon.scss.todo#L)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/date/_date.scss, line 2 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A6nhaF5RlerUmb_NB:-L3E0hxOnU_btH2ByFz5:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/date/_date.scss#L2)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Does this look OK in the PL? If not Add something like a-type--small ?
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/form-element/_form.scss, line 1 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A858GbPMO2yOUt8gl:-L3E1dWvQ-HOE60s73cX:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/_form.scss#L1)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Move to base/resets
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/form-element/_form.scss, line 61 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A7UitzlO43b8AmCIh:-L3E6LtI2IU-UUALbl05:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/_form.scss#L61)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

comment out all form focus overrides
outline and box-shadow

 resets and add a reference to this post -https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/form-element/input/_input.scss, line 5 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A8Rn40O3BtgDZFzJY:-L3E6LSq4Wdz8neZKBJy:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/input/_input.scss#L5)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

move to reset
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/form-element/input/_input.scss, line 26 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A8UUAuzRTdTnLCo1h:-L3E8WNUeS_tbpzg6iF7:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/form-element/input/_input.scss#L26)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

move to reset on input
</blockquote></details>

Done.

---

*[components/_patterns/01-atoms/table/_tables.scss, line 25 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ABgF_Jal52uMtFBrs:-L3E6l3W4nI9_GY2UXrn:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/table/_tables.scss#L25)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

600 (make all weights in this P  either 400 or 600)
</blockquote></details>

Done.

---

*[components/_patterns/02-molecules/accordion-item/accordion-item.twig, line 6 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ABskLCA6sSQYZDvZD:-L3E6tm3GSGmPFAK4S_c:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/02-molecules/accordion-item/accordion-item.twig#L6)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.

---

*[components/_patterns/08-vendor/_flickity.scss, line 1 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3ADWg21BYia9LgNzcl:-L3E9bx7tPGKNLXyTFTj:b-896fix) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/08-vendor/_flickity.scss#L1)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

REMOVE and replace with code  insert default styles from "https://flickity.metafizzy.co"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11)*
<!-- Sent from Reviewable.io -->

**Comment by finteractive** [comment]
Review status: 222 of 342 files reviewed at latest revision, 6 unresolved discussions.

---

*[components/_patterns/01-atoms/00-type/00-heading.twig, line 11 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4zxmC7W3VTZx7zTA:-L3EvS8BPwcOOpn8iKmt:bmtogxt) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/00-heading.twig#L11)):*
<details><summary><i>Previously, sgalindo2388 (Sebastian Galindo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't see it...??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11)*

**Comment by finteractive** [comment]
:lgtm:

---

Review status: 222 of 342 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-:-L3EvmNOiUfZgKbX9CiC:bnfp4nl)*

**Comment by finteractive** [comment]
Review status: 222 of 342 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/_patterns/01-atoms/00-type/00-heading.twig, line 11 at r1](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11#-L3A4zxmC7W3VTZx7zTA:-L3EvsnaCIE_gAtwn8Fp:b2ni9ah) ([raw file](https://github.com/fosterinteractive/mainspring/blob/d4b65b599b530fbb99f05d95cf26c5bdc7bd53cc/components/_patterns/01-atoms/00-type/00-heading.twig#L11)):*
<details><summary><i>Previously, finteractive (Aidan Foster) wrote…</i></summary><blockquote>

Don't see it...??
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11)*

**Comment by finteractive** [comment]
Reviewed 127 of 403 files at r1, 24 of 24 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fosterinteractive/mainspring/11)*

**Pull request merged**
